Se añade comprobacion del ar

diff --git a/Curso-Docker-Tema-9/.github/workflows/maven-CI.yml b/Curso-Docker-Tema-9/.github/workflows/maven-CI.yml
--- a/Curso-Docker-Tema-9/.github/workflows/maven-CI.yml
+++ b/Curso-Docker-Tema-9/.github/workflows/maven-CI.yml
@@ -11,33 +11,34 @@ jobs:
 
     steps:
       - name: Hacemos Checkout del repo de Git
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up JDK 8
-        uses: actions/setup-java@v1
+        uses: actions/setup-java@v3
         with:
           java-version: '8'
           distribution: 'temurin'
 
       - name: Test project with Maven
-        # Directorio de trabajo para los comandos de Maven
-        working-directory: ../mvn-hello-world
+        working-directory: "Curso-Docker-Tema-9/mvn-hello-world"
         run: mvn -B test
 
       - name: Build project with Maven
-        # Directorio de trabajo para los comandos de Maven
-        working-directory: ../mvn-hello-world
+        working-directory: "Curso-Docker-Tema-9/mvn-hello-world"
         run: mvn -B package
 
-      - name: Get Version from POM.xml
-        uses: entimaniac/read-pom-version-action@1.0.0
-        id: getVersion
+      - name: Verify .war file exists
+        run: |
+          if [ ! -f "Curso-Docker-Tema-9/mvn-hello-world/target/*.war" ]; then
+            echo "Error: No .war file found in target directory."
+            exit 1
+          fi
 
       - name: Copy generated .war to staging
-        run: mkdir staging && cp ../mvn-hello-world/target/*.war staging
+        run: mkdir -p staging && cp "Curso-Docker-Tema-9/mvn-hello-world/target/*.war" staging/
 
       - name: Upload generated .war to Artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-pages-artifact@v3
         with:
           name: mvn-hello-world-${{ steps.getVersion.outputs.version }}.zip
-          path: staging
+          path: staging/
